spring:
  cloud:
    gateway:
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins: "http://localhost:5522"
            allowedHeaders: "*"
            allowedMethods:
              -GET
              -POST
              -PUT
              -DELETE


